version: '3.8'

services:
  vocacion-plus:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - DockerDB
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ./logs:/app/logs

  DockerDB:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: VocacionPlusDB
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: