version: '3.8'

# Este archivo se utiliza con fines de desarrollo y sobrescribe la configuración predeterminada en docker-compose.yml
services:
  vocacion-plus:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "5000:8080"
    volumes:
      - .:/app
      - ~/.aspnet/https:/root/.aspnet/https:ro
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - DockerDB
